------------------------------------------
--                                      --
--              Tables TP2              -- 
--                                      --
--     Par Anthony Labelle-Voyez et     --
--            Alexis Parent             --
------------------------------------------
CREATE TABLE CATEGORIES
  (
    CodeCategorie CHAR (1) NOT NULL ,
    NomCategorie  VARCHAR2(30) ,
    Couleur       VARCHAR2(30)
  ) ;
ALTER TABLE Categories ADD CONSTRAINT Categories_PK PRIMARY KEY ( CodeCategorie ) ;

CREATE TABLE JOUEURS
  (
    ALIAS  VARCHAR2(30) NOT NULL ,
    Nom    VARCHAR2(30) ,
    Prenom VARCHAR2(30)
  ) ;
ALTER TABLE JOUEURS ADD CONSTRAINT JOUEURS_PK PRIMARY KEY ( ALIAS ) ;

CREATE TABLE MATCH
  (
    NumMatch NUMBER NOT NULL ,
    Joueur1  VARCHAR2(30) NOT NULL ,
    Joueur2  VARCHAR2(30) NOT NULL ,
    Joueur3  VARCHAR2(30) NOT NULL ,
    Joueur4  VARCHAR2(30) NOT NULL
  ) ;
ALTER TABLE MATCH ADD CONSTRAINT MATCH_PK PRIMARY KEY ( NumMatch ) ;

CREATE TABLE QUESTIONS
  (
    NumQuestion    CHAR (6) NOT NULL ,
    EnonceQuestion VARCHAR2(30) ,
    Flag           CHAR (1) ,
    CodeCategorie  CHAR (1) NOT NULL
  ) ;
ALTER TABLE QUESTIONS ADD CONSTRAINT QUESTIONS_PK PRIMARY KEY ( NumQuestion ) ;

CREATE TABLE REPONSES
  (
    NumReponse  CHAR (8) NOT NULL ,
    Description VARCHAR2(30) ,
    EstBonne    CHAR (1) ,
    NumQuestion CHAR (6) NOT NULL
  ) ;
ALTER TABLE REPONSES ADD CONSTRAINT REPONSES_PK PRIMARY KEY ( NumReponse, NumQuestion ) ;

CREATE TABLE SCORES
  (
    CodeCategorie CHAR (1) NOT NULL ,
    ALIAS         VARCHAR2(30) NOT NULL ,
    Score         NUMBER ,
    NumMatch      NUMBER NOT NULL
  ) ;
ALTER TABLE SCORES ADD CONSTRAINT SCORES_PK PRIMARY KEY ( CodeCategorie, ALIAS, NumMatch ) ;

ALTER TABLE MATCH ADD CONSTRAINT MATCH_JOUEURS_FK FOREIGN KEY ( Joueur1 ) REFERENCES JOUEURS ( ALIAS ) ;

ALTER TABLE MATCH ADD CONSTRAINT MATCH_JOUEURS_FKv1 FOREIGN KEY ( Joueur3 ) REFERENCES JOUEURS ( ALIAS ) ;

ALTER TABLE MATCH ADD CONSTRAINT MATCH_JOUEURS_FKv2 FOREIGN KEY ( Joueur4 ) REFERENCES JOUEURS ( ALIAS ) ;

ALTER TABLE MATCH ADD CONSTRAINT MATCH_JOUEURS_FKv4 FOREIGN KEY ( Joueur2 ) REFERENCES JOUEURS ( ALIAS ) ;

ALTER TABLE QUESTIONS ADD CONSTRAINT QUESTIONS_Categories_FK FOREIGN KEY ( CodeCategorie ) REFERENCES Categories ( CodeCategorie ) ;

ALTER TABLE REPONSES ADD CONSTRAINT REPONSES_QUESTIONS_FK FOREIGN KEY ( NumQuestion ) REFERENCES QUESTIONS ( NumQuestion ) ;

ALTER TABLE SCORES ADD CONSTRAINT SCORES_Categories_FK FOREIGN KEY ( CodeCategorie ) REFERENCES Categories ( CodeCategorie ) ;

ALTER TABLE SCORES ADD CONSTRAINT SCORES_JOUEURS_FK FOREIGN KEY ( ALIAS ) REFERENCES JOUEURS ( ALIAS ) ;

ALTER TABLE SCORES ADD CONSTRAINT SCORES_MATCH_FK FOREIGN KEY ( NumMatch ) REFERENCES MATCH ( NumMatch ) ;